global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'tensorflow-serving'
    static_configs:
      - targets: ['host.docker.internal:8501']

    metrics_path: '/monitoring/prometheus/metrics'  # Path harus tepat
    scrape_interval: 5s